services:
  user_services:
    build:
      context: ./user_service/
      dockerfile: Dockerfile
    ports:
      - "5062:5062"
    environment:
      - ASPNETCORE_URLS=http://+:5062
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: miniuserapp
  trip_services:
    build:
      context: ./TripsService/
      dockerfile: Dockerfile
    ports:
      - "5254:5254"
    environment:
      - ASPNETCORE_URLS=http://+:5254
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: miniserviceapp

